<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }
        body {
            
            background-color: lightpink;
        }
        .a {
            width: 1500px;
            height: 2000px;
            margin: 10px auto;

        }
        img {
            transform: rotate(20deg);


        }
        img:nth-of-type(2){
            margin-left: 25px;
            transform: rotate(-20deg);
        }
        img:nth-of-type(3){
            margin-left: 33px;
            transform: rotate(20deg);
        }
        img:nth-of-type(4){
            margin-left: 31px;
            transform: rotate(-20deg);
        }
        img:nth-of-type(5){
            margin-top: 28px;
            transform: rotate(5deg);
        }
        img:nth-of-type(6){
            margin-left: 31px;
            margin-top: 20px;
            transform: rotate(-13deg);
        }
        img:nth-of-type(7){
            margin-left: 25px;
            transform: rotate(10deg);
        }
        img:nth-of-type(8){
            margin-left: 44px;
            transform: rotate(-10deg);
        }
        img:hover {
            transform:rotate(0deg);
            transition:all 1s;
        }
        .shijian {
            width: 1200px;
            height: 100px;
            color:black;
            font-size: 100px;
            text-intend: 600px;
        }

        div {
            width: 1200px;
            height: 100px;
            color: #fdfe34;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="a">
    <img src="img/1.jpg" alt=""  width="300" height="500">
    <img src="img/2.jpg" alt=""  width="300" height="500">
    <img src="img/3.jpg" alt=""  width="300" height="500">
    <img src="img/4.jpg" alt=""  width="300" height="500">
    <img src="img/5.jpg" alt=""  width="300" height="500">
    <img src="img/6.jpg" alt=""  width="300" height="500">
    <img src="img/7.jpg" alt=""  width="300" height="500">
    <img src="img/8.jpg" alt=""  width="300" height="500">
</div>
<dia class="shijian"><p>2018.06.14</p></dia>
<div> <h1>亲爱的，我们要好好的！</h1>
    <h1>祝我们一周年快乐！</h1>
    <h1>爱你！么么哒！</h1>
</div>

</body>
</html>
